# Generated by Django 5.0.6 on 2024-05-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_theme_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='task',
            new_name='post',
        ),
    ]
